FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

# requirements.txt 파일을 복사하고 의존성 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 나머지 애플리케이션 파일 복사 (app.py, templates 폴더 등)
# .dockerignore 파일을 사용하면 좋습니다.
COPY . .

# Flask 애플리케이션이 5000번 포트를 사용하므로 노출
EXPOSE 5000

# 컨테이너 시작 시 실행할 명령어 (Flask 서버 실행)
CMD ["python", "app.py"]